language: python
python:
- '2.6'
- '2.7'
- '3.2'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
script:
- py.test
deploy:
  provider: gae
  keyfile: client-secret.json
  project: pmd-unimon
  no_promote: true
before_install:
- openssl aes-256-cbc -K $encrypted_fc7251c02568_key -iv $encrypted_fc7251c02568_iv
  -in client-secret.json.enc -out client-secret.json -d
- openssl aes-256-cbc -K $encrypted_cce5303df6ea_key -iv $encrypted_cce5303df6ea_iv
  -in client-secret.json.enc -out client-secret.json -d
