
application: pmd-unimon
runtime: python27
api_version: 1
threadsafe: true

# ---------- ---------- ---------- ---------- ----------

version: 2017-01-xx
#
# TODO:
# xxx
#
# Major Changes:
# Framework of application developed
# Travis CI builds and autodeploy to GAE
#
# Minor Changes:
# xxx

# ---------- ---------- ---------- ---------- ----------

handlers:
- url: /css
  static_dir: resources/css
- url: /html
  static_dir: resources/html
- url: /js
  static_dir: resources/js
- url: /.*
  script: main.application
